// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 40: // ['(','(']
			return 1
		case r == 41: // [')',')']
			return 2
		case 48 <= r && r <= 57: // ['0','9']
			return 3
		case 65 <= r && r <= 90: // ['A','Z']
			return 3
		case 97 <= r && r <= 122: // ['a','z']
			return 3
		case r == 123: // ['{','{']
			return 4
		case r == 125: // ['}','}']
			return 5
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		case r == 102: // ['f','f']
			return 6
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 41: // [')',')']
			return 7
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 3
		case 65 <= r && r <= 90: // ['A','Z']
			return 3
		case 97 <= r && r <= 122: // ['a','z']
			return 3
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 117: // ['u','u']
			return 8
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 110: // ['n','n']
			return 9
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 99: // ['c','c']
			return 10
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 58: // [':',':']
			return 11
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
