// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(2), /* { */
			nil,      /* label */
			nil,      /* } */
			nil,      /* (func: */
			nil,      /* ( */
			nil,      /* )) */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* { */
			nil,          /* label */
			nil,          /* } */
			nil,          /* (func: */
			nil,          /* ( */
			nil,          /* )) */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* { */
			shift(3), /* label */
			nil,      /* } */
			nil,      /* (func: */
			nil,      /* ( */
			nil,      /* )) */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* { */
			nil,      /* label */
			nil,      /* } */
			shift(5), /* (func: */
			nil,      /* ( */
			nil,      /* )) */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(6), /* { */
			nil,      /* label */
			nil,      /* } */
			nil,      /* (func: */
			nil,      /* ( */
			nil,      /* )) */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* { */
			shift(8), /* label */
			nil,      /* } */
			nil,      /* (func: */
			nil,      /* ( */
			nil,      /* )) */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* { */
			shift(9), /* label */
			nil,      /* } */
			nil,      /* (func: */
			nil,      /* ( */
			nil,      /* )) */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* { */
			nil,       /* label */
			shift(11), /* } */
			nil,       /* (func: */
			nil,       /* ( */
			nil,       /* )) */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* { */
			nil,       /* label */
			nil,       /* } */
			nil,       /* (func: */
			shift(12), /* ( */
			nil,       /* )) */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* { */
			nil,       /* label */
			reduce(4), /* }, reduce: FuncBlock */
			nil,       /* (func: */
			nil,       /* ( */
			nil,       /* )) */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* { */
			nil,       /* label */
			shift(13), /* } */
			nil,       /* (func: */
			nil,       /* ( */
			nil,       /* )) */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: Query */
			nil,       /* { */
			nil,       /* label */
			nil,       /* } */
			nil,       /* (func: */
			nil,       /* ( */
			nil,       /* )) */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* { */
			shift(14), /* label */
			nil,       /* } */
			nil,       /* (func: */
			nil,       /* ( */
			nil,       /* )) */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* { */
			nil,       /* label */
			reduce(3), /* }, reduce: FuncBody */
			nil,       /* (func: */
			nil,       /* ( */
			nil,       /* )) */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* { */
			nil,       /* label */
			nil,       /* } */
			nil,       /* (func: */
			nil,       /* ( */
			shift(15), /* )) */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			reduce(2), /* {, reduce: Func */
			nil,       /* label */
			nil,       /* } */
			nil,       /* (func: */
			nil,       /* ( */
			nil,       /* )) */
		},
	},
}
