// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 5

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Query
		4,  // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Query
		-1, // Func
		7,  // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		10, // FuncBlock
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Query
		-1, // Func
		-1, // FuncBody
		-1, // FuncBlock
	},
}
