// Code generated by gocc; DO NOT EDIT.

package parser

import "github.com/dgraph-io/dgraph/parser/ast"

type (
	//TODO: change type and variable names to be consistent with other tables
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Query	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Query : "{" label Func FuncBody "}"	<< ast.NewGraphQuery(X[1]) >>`,
		Id:         "Query",
		NTType:     1,
		Index:      1,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewGraphQuery(X[1])
		},
	},
	ProdTabEntry{
		String: `Func : "(func:" label "(" label "))"	<<  >>`,
		Id:         "Func",
		NTType:     2,
		Index:      2,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FuncBody : "{" FuncBlock "}"	<<  >>`,
		Id:         "FuncBody",
		NTType:     3,
		Index:      3,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FuncBlock : label	<<  >>`,
		Id:         "FuncBlock",
		NTType:     4,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
}
