_achar: 'a' - 'z' | 'A'-'Z' | '0'-'9' | '_';
label :  _achar {_achar};

!whitespace : '\t' | '\n' | '\r' | ' ';

/*Syntax part*/
<< import "github.com/dgraph-io/dgraph/parser/ast" >>

Query : "{" label  Func  FuncBody "}" << ast.NewGraphQuery($1) >>;

Func : "(func:" label "(" label "))";

FuncBody: "{" FuncBlock "}";

FuncBlock: label;